### ISSUE TITLE
Cannot install pybluez

### ISSUE THREAD

**Issue by iris-pascoal** [BITalinoWorld/revolution-python-api#10]
HI! I try following the instructions and downloaded visual studio 2015 from the link you provide but the installation always says that there are missing files.

I also tried downloading from the visual studio website and followed the remaining steps. When i do this and then run pip install pybluez-win10 i get the error:

ERROR: Could not find a version that satisfies the requirement pybluez-win10 (from versions: none)
ERROR: No matching distribution found for pybluez-win10

**Comment by GRamosPlux** [comment]
Dear @iris-pascoal,

Thank you very much for opening this issue, the team will be pleased to provide some guidance about this extremely relevant topic.

First of all, our sincere apologies for this undesirable event, unfortunately, the **README.md** file segment regarding the **pybluez-win10** is outdated, we will immediately proceed to the update of the page!

Concerning the installation of **PyBluez**, sometimes installing directly through **pip** is a little bit tricky.
In these circumstances, installing the version available in the **PyBluez GitHub Repository** is generally a viable workaround.
It is with great pleasure that we share the following illustrative video: 

https://user-images.githubusercontent.com/49654007/153282570-273ef4d1-a59b-411a-a5a1-d95f1e24e077.mp4

I will carefully wait for your extremely valuable feedback about the effectiveness of the previous workaround!

**My best and sincere regards,**
@GRamosPlux

**Comment by iris-pascoal** [comment]
Thank you for the video. The installation worked!

**Comment by GRamosPlux** [comment]
Dear  @iris-pascoal,

These are excellent news, we are really happy for understanding that the previous workaround was effective in overtaking the reported obstacle.

Thank you very much for your important feedback!

We will close this topic, please, do not hesitate to create a new issue if any additional question arises.

In the meantime, let me wish you a continuation of exciting discoveries in the **BITalino World**.

**My best and sincere regards,**
@GRamosPlux
