### ISSUE TITLE
Serial.read() running indefinitely

### ISSUE THREAD

**Issue by CharlesEmileG** [BITalinoWorld/revolution-python-api#15]
Serial.read() is running forever. I am using OS Ventura, and even if the device is recognized, nothing is read.

<img width="1006" alt="Screenshot 2023-02-02 at 12 16 58 PM" src="https://user-images.githubusercontent.com/123205745/216395697-1e110480-8db4-46c0-85ae-35a166221edb.png">

**Comment by DFNOsorio** [comment]
Unfortunately, with the new release of MacOS, the serial port method to connect to Bitalino is broken. 

We recommend using [Plux Pythons API ](https://github.com/pluxbiosignals/python-samples)to interact with your BITalino.
